Algoritmo "DOR_DEPRESSÃO_E_SOFRIMENTO_23"

Var

n1, n2, n3, n4, n5, media: real

Inicio

escreva ("Insira o 1° número: ")
leia (n1)
escreva ("Insira o 2° número: ")
leia (n2)
escreva ("Insira o 3° número: ")
leia (n3)
escreva ("Insira o 4° número: ")
leia (n4)
escreva ("Insira o 5° número: ")
leia (n5)


media <- (n1 + n2 + n3 + n4 +n5) / 5

escreva ("A média destes valores é de:", media)

Fimalgoritmo