Algoritmo "DOR_DEPRESSÃO_E_SOFRIMENTO_16"

Var

lado1, lado2, lado3: real

Inicio

escreva ("Insira o valor do 1° lado do triangulo: ")
leia (lado1)
escreva ("Insira o valor do 2° lado do triangulo: ")
leia (lado2)
escreva ("Insira o valor do 3° lado do triangulo: ")
leia (lado3)

se (lado1 + lado2 > lado3) entao
   escreva ("este triângulo é valido :)")
senao
     escreva ("este triângulo não é valido >:(")
fimse

Fimalgoritmo