Algoritmo "DOR_DEPRESSÃO_E_SOFRIMENTO_10"

Var

n1: inteiro
n2: inteiro


Inicio

escreva ("Insira o 1° número: ")
leia (n1)
escreva ("Insira o 2° número: ")
leia (n2)

se (n1 > n2) entao
   escreva ("O primeiro número é maior")
senao
se (n2 > n1) entao
      escreva ("O segundo número é maior")
senao
se (n1 = n2) entao
      escreva ("Os dois números são iguais")
fimse
fimse
fimse

Fimalgoritmo